apiVersion: v1
kind: Service
metadata:
  labels:
      run: asynccnu-table
  name: asynccnu-table
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: asynccnu-table
